### ISSUE TITLE
Planner error: `Alias can not contain multiple parts (dots)`

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#131]
This query:
```
plan = plan_query(
            'SELECT * FROM chmain.test_data.test_view left join mindsdb.ontime_test4 AS tb WHERE tb.fecha > LATEST',
            integrations=['chmain'],
            predictor_namespace='mindsdb',
            predictor_metadata='{'ontime_test4': {'timeseries': True, 'window': 3, 'order_by_column': 'fecha', 'group_by_column': 'IATA_CODE_Reporting_Airline'}}',
            default_namespace='mindsdb'
        )
```
Cause error:
```
Alias can not contain multiple parts (dots).
Traceback (most recent call last):
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb/mindsdb/api/mysql/mysql_proxy/mysql_proxy.py", line 2277, in handle
    self.query_answer(sql)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb/mindsdb/api/mysql/mysql_proxy/mysql_proxy.py", line 1427, in query_answer
    query = SQLQuery(
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 153, in __init__
    self._parse_query(sql)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb/mindsdb/api/mysql/mysql_proxy/classes/sql_query.py", line 308, in _parse_query
    plan = plan_query(
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/__init__.py", line 5, in plan_query
    return QueryPlan(*args, **kwargs).from_query(query)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/query_plan.py", line 439, in from_query
    self.plan_select(query)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/query_plan.py", line 427, in plan_select
    return self.plan_join(query)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/query_plan.py", line 382, in plan_join
    last_step = self.plan_join_table_and_timeseries_predictor(query, table, predictor_namespace, predictor)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/query_plan.py", line 301, in plan_join_table_and_timeseries_predictor
    right=Identifier(predictor_inputs.ref_name,
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/parser/ast/select/identifier.py", line 18, in __init__
    super().__init__(*args, **kwargs)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/parser/ast/base.py", line 11, in __init__
    raise ParsingException('Alias can not contain multiple parts (dots).')
mindsdb_sql.exceptions.ParsingException: Alias can not contain multiple parts (dots).
```
If first tale in query have alias, then all pass file:
```
SELECT * FROM chmain.test_data.test_view as ta left join mindsdb.ontime_test4 AS tb WHERE tb.fecha > LATEST
```

**Comment by ea-rus** [comment]
43b964ff
