### ISSUE TITLE
support `CREATE predictor....` query in planner

### ISSUE THREAD

**Issue by ilia-tsyplenkov** [mindsdb/mindsdb_sql#204]
currently planner doesn't support such queries and throws an exception for similar code:
```
from mindsdb_sql import parse_sql                                      
from mindsdb_sql.planner import plan_query
from mindsdb_sql.parser.ast import *
from mindsdb_sql.parser.dialects.mysql import Variable
from mindsdb_sql.parser.dialects.mindsdb import *


query = "CREATE PREDICTOR hr from MYSQL (select * from test_data.home_rentals) as hr_ds predict rental_price"      

parsed = parse_sql(query, dialect='mindsdb')
plan = plan_query(parsed, default_namespace='mindsdb', integrations=['mindsdb', ])
```

```
Traceback (most recent call last):
  File "tmp2.py", line 56, in <module>
    plan = plan_query(parsed, default_namespace='mindsdb', integrations=['mindsdb', ])
  File "/home/itsyplen/repos/work/MindsDB/mindsdb_sql/mindsdb_sql/planner/__init__.py", line 5, in plan_query
    return QueryPlanner(query, *args, **kwargs).from_query()
  File "/home/itsyplen/repos/work/MindsDB/mindsdb_sql/mindsdb_sql/planner/query_planner.py", line 567, in from_query
    raise PlanningException(f'Unsupported query type {type(query)}')
mindsdb_sql.exceptions.PlanningException: Unsupported query type <class 'mindsdb_sql.parser.dialects.mindsdb.create_predictor.CreatePredictor'>
```

**Comment by ea-rus** [comment]
It could be a lot of extra code to wrap every of this commands in its own step.
- CreateDatasource
- DropPredictor
- DropTables
- DropDatasource
and so on

Because at the moment there is no logic that can be shared between them. Even create_predictor function must contain logic of extraction data inside it because it is more optimal to get data from datasource as stream.

As compromise we can create something like SqlCommandStep (and save AST-query inside it) to accumulate all logic that dependend from type of AST-class.

**Comment by ea-rus** [comment]
I think we can close this issue.
