### ISSUE TITLE
Exception if table specified without database

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#50]
```
parse_sql("SELECT status FROM predictors where name = 'home_rentals_predictor'", dialect='mindsdb')
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/__init__.py", line 25, in parse_sql
    ast = parser.parse(tokens)
  File "/home/maxs/dev/mdb/venv38/lib/python3.8/site-packages/sly-0.4-py3.8.egg/sly/yacc.py", line 2119, in parse
    tok = self.error(errtoken)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/parser/dialects/mindsdb/parser.py", line 432, in error
    raise ParsingException(f"Syntax error at token {p.type}: \"{p.value}\"")
mindsdb_sql.exceptions.ParsingException: Syntax error at token PREDICTORS: "predictors"
```

**Comment by btseytlin** [comment]
This is not a bug. `predictor` and `predictors` are keywords in mindsdb dialect, so they are not allowed as identifiers, just like you can't have a table named table.

**Comment by btseytlin** [comment]
We will have to find a workaround to have it work, as people will want to do  `use mindsdb; SELECT * FROM predictors WHERE`

**Comment by btseytlin** [comment]
Found a workaround:
https://github.com/mindsdb/mindsdb_sql/pull/57

**Comment by btseytlin** [comment]
Resolved
