### ISSUE TITLE
Exception if two values are compared in 'WHERE'

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#53]
Same as in [here](https://github.com/mindsdb/dfsql/issues/37), if query have '1 = 0' then exception occurs in planner
```
plan_query(
            parse_sql('''SELECT GDP_per_capita_USD FROM hdi_predictor_external WHERE 1 = 0''', dialect='mindsdb')
            integrations=integrations_names,
            predictor_namespace=self.mindsdb_database_name,
            predictor_metadata=predictor_metadata,
            default_namespace=self.database
        )
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/__init__.py", line 5, in plan_query
    return QueryPlan(*args, **kwargs).from_query(query)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/query_plan.py", line 426, in from_query
    self.plan_select(query)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/query_plan.py", line 408, in plan_select
    return self.plan_select_from_predictor(query)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/query_plan.py", line 136, in plan_select_from_predictor
    recursively_extract_column_values(where_clause, row_dict, predictor)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/utils.py", line 166, in recursively_extract_column_values
    id = disambiguate_predictor_column_identifier(op.args[0], predictor)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/planner/utils.py", line 72, in disambiguate_predictor_column_identifier
    parts = list(identifier.parts)
AttributeError: 'Constant' object has no attribute 'parts'
```

**Comment by btseytlin** [comment]
Working on this in branch bugfix-53, but I need to know what plan should be returned for this query
