### ISSUE TITLE
Error if table name is 'tables'

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_sql#62]
```
parse_sql("SELECT * FROM tables")
```
leads to
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/__init__.py", line 25, in parse_sql
    ast = parser.parse(tokens)
  File "/home/maxs/dev/mdb/venv38/lib/python3.8/site-packages/sly-0.4-py3.8.egg/sly/yacc.py", line 2119, in parse
    tok = self.error(errtoken)
  File "/home/maxs/dev/mdb/venv38/sources/mindsdb_sql/mindsdb_sql/parser/parser.py", line 508, in error
    raise ParsingException(f"Syntax error at token {p.type}: \"{p.value}\"")
mindsdb_sql.exceptions.ParsingException: Syntax error at token TABLES: "tables"
```

**Comment by btseytlin** [comment]
Resolved in https://github.com/mindsdb/mindsdb_sql/pull/63
